In [2]:
import numpy as np

# X - Restaurants x Users
# Each row corresponds to user vector
X = np.asarray([[5,5,0,0],[5,0,0,0],[0,4,0,0],[0,0,5,4],[0,0,5,0]])

# Y is Feature vector of all restaurants. One row is a single feature vector
# of one restaurant. Number of features = 2
Y = np.transpose(np.asarray(
[[ 0.9, 0 ],
 [ 1, 0.01],
 [ 0.99 , 0],
 [ 0.1  , 1],
 [ 0   ,0.9]]))

print Y
print X
# print np.random.randn(10) #y
# print np.random.randn(10, 5) #x

[[ 0.9   1.    0.99  0.1   0.  ]
 [ 0.    0.01  0.    1.    0.9 ]]
[[5 5 0 0]
 [5 0 0 0]
 [0 4 0 0]
 [0 0 5 4]
 [0 0 5 0]]


In [37]:
# X  = feature vector of restaurants

X = np.asarray(
[[ 0.9, 0 ],
 [ 1, 0.01],
 [ 0.99 , 0],
 [ 0.1  , 1],
 [ 0   ,0.9]])

# Y = rating of user j on restaurant i

Y = np.transpose(np.asarray([[5,5,0,0],[5,0,0,0],[0,4,0,0],[0,0,5,4],[0,0,5,0]]))

# print X
# print X.shape
print X
# print Y
print Y

[[ 0.9   0.  ]
 [ 1.    0.01]
 [ 0.99  0.  ]
 [ 0.1   1.  ]
 [ 0.    0.9 ]]
[[5 5 0 0 0]
 [5 0 4 0 0]
 [0 0 0 5 5]
 [0 0 0 4 0]]


In [46]:
Y.shape

(4L, 5L)

In [35]:
# Running gradient descent on one feature of business
from sklearn import linear_model

model = linear_model.SGDRegressor()
# Here Y[0] indicates first feature of the business.
model.fit(X, Y[0])


SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', n_iter=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, verbose=0, warm_start=False)

In [36]:
model.coef_

array([ 0.25817415, -0.00689859])

In [38]:
# Our parameters needed

user_params_feature1 = model.coef_

In [56]:
# Here Y[1] indicates second feature of the business.
user_params = []
for i in range(int(Y.shape[0])):
    model.fit(X, Y[i])
    user_params.append(np.asarray(model.coef_))
user_params =  np.asarray(user_params)

In [57]:
# Here Y[0] indicates one feature of the business.
# model.fit(X, Y[0])

In [58]:
# # Our parameters needed

# user_params_feature2 = model.coef_

# zip(user_params_feature1, user_params_feature2)

In [60]:
# user_params = np.asarray([list(item) for item in user_params])

# user_params = user_params
user_params.dot(X.T)

array([[ 0.23116256,  0.25678378,  0.25427882,  0.01933374, -0.00571589],
       [ 0.20275344,  0.22521347,  0.22302879,  0.015715  , -0.00613185],
       [ 0.00193066,  0.00481174,  0.00212373,  0.26687048,  0.23999037],
       [ 0.00582771,  0.00758933,  0.00641048,  0.11205778,  0.10026923]])